Enable tofi calls in CMOS camera
analogdevicesinc/aditof-sdk-rework pull request #12
Opened 2021-03-03 10:32 UTC by SeptimiuVana

Signed-off-by: SeptimiuVana <Vana.Septimiu@analog.com>

2021-03-03 16:10 UTC, MccartyADI commented
We should talk before moving forward.  We should not use the term 'cmos' in this code to refer to the sensor.

2021-03-08 07:11 UTC, dNechita requested changes

2021-03-08 07:11 UTC, dNechita commented on sdk/CMakeLists.txt
> +    target_link_libraries(${PROJECT_NAME} PUBLIC libtofi_compute)
What is the reason for using 'PUBLIC'? I believe 'PRIVATE' should be used both here and for the libtofi_config, because libtofi is used only internally by the camera implementation.

2021-03-08 07:11 UTC, dNechita commented on sdk/CMakeLists.txt
> +    set(libtofi "${CMAKE_SOURCE_DIR}/../libs")
Can you rename this to: LIBTOFI_LIBDIR_PATH so the name it's more descriptive.

2021-03-08 07:11 UTC, dNechita commented on sdk/CMakeLists.txt
> +    set(libtofi "${CMAKE_SOURCE_DIR}/../libs")
Also can you first check if variable is not defined and only then set it? This would allow overriding the variable value when executing cmake.

2021-03-08 07:11 UTC, dNechita commented on sdk/CMakeLists.txt
> +             IMPORTED_NO_SONAME 2
Why 2?

2021-03-08 07:22 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.h
> +    uint8_t convertCameraMode(std::string modes);
Use a constant reference when passing a string. This practice prevents the string parameter to be copied on the stack.

2021-03-08 07:22 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.cpp
> +    return (aditof::Status::GENERIC_ERROR);
This method has 2 returns. Doesn't look right.

2021-03-08 07:22 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.cpp
> +        return 0;
So if getAvailableModes() fails, mode 0 will be returned and we won't know there was an error.

2021-03-08 07:59 UTC, dNechita commented on sdk/CMakeLists.txt
> +#libtofi - path to libtofi_config.so and libtofi_compute.so folder
Please update this comment as well

2021-03-08 08:09 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.h
> +    uint8_t convertCameraMode(std::string &modes) const;
Does the implantation of this function modify the string? if not, please use a constant reference.

2021-03-08 08:12 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.cpp
> +        return -1;
You can't return -1. You have declared that this function returns an unsigned integer type.

2021-03-08 08:12 UTC, dNechita commented on sdk/src/cameras/cmos-camera/camera_cmos.cpp
> +    auto it = std::find (availableModes.begin(), availableModes.end(), modes);
What happens if mode is not found?

2021-03-08 13:31 UTC, MccartyADI commented on sdk/CMakeLists.txt
> +    target_link_libraries(${PROJECT_NAME} PUBLIC libtofi_compute)
For now yes that's correct, however but we likely need to have a passthrough API for the depth compute interface, for example the evaluation GUI needs to be able to "playback" recorded raw files by calling depth compute without camera.

2021-03-08 15:06 UTC, dNechita commented on sdk/CMakeLists.txt
> +    target_link_libraries(${PROJECT_NAME} PUBLIC libtofi_compute)
I understand. We will keep it private for now but I've created an issue to track the feature you mentioned.

2021-03-09 08:53 UTC, merged