Mode5 bringup
analogdevicesinc/aditof-sdk-rework pull request #80
Opened 2021-05-24 10:29 UTC by VLitanADI

Implement necessary changes in order to run mode 5 .

2021-05-24 14:29 UTC, dNechita requested changes

2021-05-24 14:29 UTC, dNechita commented on examples/first-frame/main.cpp
> +    std::ofstream g(std::string(PROJECT_DIR) + "/build/out_" + frameType + "_" + fDetails.type + ".bin", std::ios::binary);
Don't add PROJECT_DIR + "build/out". PROJECT_DIR won't work if the executable of this examples is ran on other machines and if at some point in time, the PROJECT_DIR is deleted. "build/out" won't work for anybody who named the build directory anything else than "build". Just let the generated file be created next to the executable.

2021-05-24 14:29 UTC, dNechita commented on sdk/src/cameras/itof-camera/camera_itof.cpp
> +if (status != Status::OK) {
fix indentation

2021-05-24 14:29 UTC, dNechita commented on sdk/src/connections/target/adsd3100_sensor.cpp
> +#define EXTRA_BUFFERS_COUNT 0
Can you add a description of when and why this might be needed?

2021-05-24 14:29 UTC, dNechita commented on sdk/src/connections/target/adsd3100_sensor.cpp
> +    std::ofstream g(std::string(PROJECT_DIR) + "/build/out" + id + ".bin", std::ios::binary);
Same as my comment on the first-frame example. Use relative paths. It's enough to provide just the name of the file to save.

2021-05-25 12:38 UTC, VLitanADI commented on sdk/src/connections/target/adsd3100_sensor.cpp
> +    std::ofstream g(std::string(PROJECT_DIR) + "/build/out" + id + ".bin", std::ios::binary);
done

2021-05-25 12:38 UTC, VLitanADI commented on examples/first-frame/main.cpp
> +    std::ofstream g(std::string(PROJECT_DIR) + "/build/out_" + frameType + "_" + fDetails.type + ".bin", std::ios::binary);
done

2021-05-25 12:41 UTC, VLitanADI commented on sdk/src/connections/target/adsd3100_sensor.cpp
> +#define EXTRA_BUFFERS_COUNT 0
done

2021-05-25 12:45 UTC, VLitanADI commented on sdk/src/cameras/itof-camera/camera_itof.cpp
> +if (status != Status::OK) {
fixed

2021-05-26 06:54 UTC, SeptimiuVana approved these changes

2021-05-26 07:37 UTC, dNechita approved these changes

2021-05-26 07:50 UTC, merged